{
  description = "Niri NixOS VM for Apple Silicon";

  # We use nixos-unstable because Niri is a fast-moving project
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
  };

  outputs = {
    self,
    nixpkgs,
    ...
  }: let
    settings = import ./settings.nix;
  in {
    nixosConfigurations.${settings.configName} = nixpkgs.lib.nixosSystem {
      system = "aarch64-linux"; # Apple Silicon
      modules = [
        # Import the hardware config generated by the installer
        ./hardware-configuration.nix

        (
          {pkgs, ...}: {
            # Networking
            networking.hostName = settings.hostName;
            networking.networkmanager.enable = true;

            # Bootloader
            # Systemd-boot is standard for UEFI on VMware Fusion
            boot.loader.systemd-boot.enable = true;
            boot.loader.efi.canTouchEfiVariables = true;

            # VMware Guest Support
            # Enables clipboard sharing, resizing, and mouse integration
            virtualisation.vmware.guest.enable = true;

            # Niri requires hardware graphics support.
            # Note: In NixOS unstable, 'hardware.opengl' is renamed to 'hardware.graphics'
            hardware.graphics.enable = true;

            # Localization
            time.timeZone = settings.timezone;
            i18n.defaultLocale = settings.locale;
            console = {
              font = settings.consoleFont;
              keyMap = settings.consoleKeyMap;
            };

            # User
            users.users.${settings.userName} = {
              isNormalUser = true;
              extraGroups = [
                "wheel"
                "networkmanager"
                "video"
              ];
              password = "nixos"; # Temporary password for testing
            };

            # Niri
            programs.niri.enable = true;

            # Enable sound
            security.rtkit.enable = true;
            services.pipewire = {
              enable = true;
              alsa.enable = true;
              pulse.enable = true;
            };

            # System packages
            environment.systemPackages = with pkgs; [
              # Niri Essentials (Terminal & Launcher are NOT included by default)
              alacritty # Terminal emulator
              fuzzel # App launcher
              waybar # Status bar
              mako # Notification daemon

              # Tools & Apps
              firefox
              wl-clipboard # Required for clipboard sharing

              # Development / Utilities (Requested)
              emacs
              git
              tree
              curl
              vim
            ];

            # --- VM Compatibility Optimizations ---
            environment.sessionVariables = {
              # Fixes invisible cursor in Wayland VMs
              WLR_NO_HARDWARE_CURSORS = "1";

              # Hint to Electron apps (VS Code, etc) to use Wayland
              NIXOS_OZONE_WL = "1";

              # DEBUGGING: If you get a black screen on boot, uncomment the line below.
              # It forces software rendering. It is slow, but guarantees the VM will display.
              # WLR_RENDERER = "pixman";
            };

            # --- Display Manager ---
            # GDM (GNOME Display Manager) is the most reliable login screen for Wayland
            services.xserver.enable = true;
            services.displayManager.gdm.enable = true;

            # --- State Version ---
            system.stateVersion = "25.11";
          }
        )
      ];
    };
  };
}
